### ISSUE TITLE
Segment Fault when Calling MLSL::Environment::GetProcessIdx()

### ISSUE THREAD

**Issue by edwardbadboy** [intel/MLSL#11]
Hi!
I'm using Intel Caffe-1.0.6 with l_mlsl_2017.1.016.

When I tried to run a simple Python program utilizing pycaffe to train lenet over mnist, it triggers segmentation fault in MLSL.

The python program is as follow:

```
import caffe
import numpy as np
import matplotlib.pyplot as plt
from caffe import layers as L, params as P
from pylab import *

def lenet(lmdb, batch_size):
    n = caffe.NetSpec()
    n.data, n.label = L.Data(batch_size=batch_size, backend=P.Data.LMDB, source=lmdb,
                             transform_param=dict(scale=1./255), ntop=2)
    n.conv1 = L.Convolution(n.data, kernel_size=5, num_output=20, weight_filler=dict(type='xavier'))
    n.pool1 = L.Pooling(n.conv1, kernel_size=2, stride=2, pool=P.Pooling.MAX)
    n.conv2 = L.Convolution(n.pool1, kernel_size=5, num_output=50, weight_filler=dict(type='xavier'))
    n.pool2 = L.Pooling(n.conv2, kernel_size=2, stride=2, pool=P.Pooling.MAX)
    n.fc1 =   L.InnerProduct(n.pool2, num_output=500, weight_filler=dict(type='xavier'))
    n.relu1 = L.ReLU(n.fc1, in_place=True)
    n.score = L.InnerProduct(n.relu1, num_output=10, weight_filler=dict(type='xavier'))
    n.loss =  L.SoftmaxWithLoss(n.score, n.label)
    return n.to_proto()

def main():
    caffe_root = '/root/zhengsheng/caffe-1.0.6/'
    caffe.set_mode_cpu()
    with open('mnist/lenet_auto_train.prototxt', 'w') as f:
        f.write(str(lenet('mnist/mnist_train_lmdb', 64)))
    with open('mnist/lenet_auto_test.prototxt', 'w') as f:
        f.write(str(lenet('mnist/mnist_test_lmdb', 100)))
    print 'loading solver'
    solver = None
    solver = caffe.SGDSolver('mnist/lenet_auto_solver.prototxt')
    niter = 200
    test_interval = 25
    # losses will also be stored in the log
    train_loss = zeros(niter)
    test_acc = zeros(int(np.ceil(niter / test_interval)))
    output = zeros((niter, 8, 10))
    print 'starting loop'
    for it in range(niter):
        solver.step(1)  # SGD by Caffe
        train_loss[it] = solver.net.blobs['loss'].data
        solver.test_nets[0].forward(start='conv1')
        output[it] = solver.test_nets[0].blobs['score'].data[:8]
        if it % test_interval == 0:
            print 'Iteration', it, 'testing...'
            correct = 0
            for test_it in range(100):
                solver.test_nets[0].forward()
                correct += sum(solver.test_nets[0].blobs['score'].data.argmax(1)
                               == solver.test_nets[0].blobs['label'].data)
            print 'Acc:', correct
            test_acc[it // test_interval] = correct / 1e4

if __name__ == '__main__':
    exit(main())
```

where the solver mentioned in the code 'mnist/lenet_auto_solver.prototxt' comes from [lenet_auto_solver.prototxt](https://github.com/intel/caffe/blob/1.0.6/examples/mnist/lenet_auto_solver.prototxt). I just appended a line "solver_mode: CPU" at the tail of the solver file.

and the traceback is as this:
```
#0  0x00007fc10af17bca in MLSL::Environment::GetProcessIdx() ()
   from /root/zhengsheng/caffe-1.0.6/external/mlsl/l_mlsl_2017.1.016/intel64/lib/libmlsl.so.1
#1  0x00007fc10b798c23 in caffe::ReplaceMultinodeSolverParams(caffe::SolverParameter*) ()
   from /root/zhengsheng/caffe-1.0.6/distribute/lib/libcaffe.so.1.0.0-rc3
#2  0x00007fc10b6f6a89 in caffe::Solver<float>::Init(caffe::SolverParameter const&) ()
   from /root/zhengsheng/caffe-1.0.6/distribute/lib/libcaffe.so.1.0.0-rc3
#3  0x00007fc10b6f73c3 in caffe::Solver<float>::Solver(std::string const&, caffe::Solver<float> const*) ()
   from /root/zhengsheng/caffe-1.0.6/distribute/lib/libcaffe.so.1.0.0-rc3
#4  0x00007fc10bba8fcd in boost::python::objects::make_holder<1>::apply<boost::python::objects::pointer_holder<boost::shared_ptr<caffe::SGDSolver<float> >, caffe::SGDSolver<float> >, boost::mpl::vector1<std::string> >::execute(_object*, std::string) ()
   from /root/zhengsheng/caffe-1.0.6/distribute/python/caffe/_caffe.so
#5  0x00007fc10bb7f3a3 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (*)(_object*, std::string), boost::python::default_call_policies, boost::mpl::vector3<void, _object*, std::string> > >::operator()(_object*, _object*) ()
   from /root/zhengsheng/caffe-1.0.6/distribute/python/caffe/_caffe.so
#6  0x00007fc1084b629c in boost::python::objects::function::call(_object*, _object*) const () from /lib64/libboost_python.so.1.53.0
#7  0x00007fc1084b65f8 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) () from /lib64/libboost_python.so.1.53.0
#8  0x00007fc1084beec3 in boost::python::handle_exception_impl(boost::function0<void>) () from /lib64/libboost_python.so.1.53.0
#9  0x00007fc1084b4df9 in function_call () from /lib64/libboost_python.so.1.53.0
#10 0x00007fc14e2d99a3 in PyObject_Call (func=func@entry=<Boost.Python.function at remote 0x19ae950>, arg=arg@entry=
    (<SGDSolver at remote 0x42c8838>, 'mnist/lenet_auto_solver.prototxt'), kw=kw@entry=0x0) at /usr/src/debug/Python-2.7.5/Objects/abstract.c:2529
#11 0x00007fc14e2e8995 in instancemethod_call (func=<Boost.Python.function at remote 0x19ae950>, 
    arg=(<SGDSolver at remote 0x42c8838>, 'mnist/lenet_auto_solver.prototxt'), kw=0x0) at /usr/src/debug/Python-2.7.5/Objects/classobject.c:2602
#12 0x00007fc14e2d99a3 in PyObject_Call (func=func@entry=<instancemethod at remote 0x4012050>, arg=arg@entry=('mnist/lenet_auto_solver.prototxt',), 
    kw=kw@entry=0x0) at /usr/src/debug/Python-2.7.5/Objects/abstract.c:2529
#13 0x00007fc14e330947 in slot_tp_init (self=<optimized out>, args=('mnist/lenet_auto_solver.prototxt',), kwds=0x0)
    at /usr/src/debug/Python-2.7.5/Objects/typeobject.c:5692
#14 0x00007fc14e32f65f in type_call (type=<optimized out>, args=('mnist/lenet_auto_solver.prototxt',), kwds=0x0)
    at /usr/src/debug/Python-2.7.5/Objects/typeobject.c:745
#15 0x00007fc14e2d99a3 in PyObject_Call (func=func@entry=<Boost.Python.class at remote 0x19b01a0>, 
    arg=arg@entry=('mnist/lenet_auto_solver.prototxt',), kw=kw@entry=0x0) at /usr/src/debug/Python-2.7.5/Objects/abstract.c:2529
#16 0x00007fc14e36e0f6 in do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7fff132eae00, func=<optimized out>)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:4626
#17 call_function (oparg=<optimized out>, pp_stack=0x7fff132eae00) at /usr/src/debug/Python-2.7.5/Python/ceval.c:4431
#18 PyEval_EvalFrameEx (f=f@entry=
.... # lots of python interpreter call stacks
```

It looks like that the python statement
`solver = caffe.SGDSolver('mnist/lenet_auto_solver.prototxt')`
triggers the segmentation fault.

However, if I use caffe.bin to train the model using the same solver file, it runs successfully. The command is like follow.
```
cd caffe-1.0.6/examples
../distribute/bin/caffe.bin train -solver=mnist/lenet_auto_solver.prototxt
```

As regard to the phisycal machine CPU, lscpu shows:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2730.843
CPU max MHz:           3200.0000
CPU min MHz:           1200.0000
BogoMIPS:              4799.86
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-5,12-17
NUMA node1 CPU(s):     6-11,18-23
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc
```

Is this problem solved in the latest release? Maybe I can just try  l_mlsl_2017.1.016 ?

Thank you very much!

**Comment by mshiryaev** [comment]
Hi @edwardbadboy. I would suggest to ask Intel Caffe team directly about that issue.
https://github.com/intel/caffe

**Comment by edwardbadboy** [comment]
Thank you @mshiryaev . I went through pycaffe code in Intel Caffe, I found that there was no code related to initiating MLSL.
